#!/bin/bash
export PATH="$HOME/sh/tools:$PATH"
export PATH="$HOME/sh:$PATH"
cd $HOME/sh/app/open_pro
source e2s config

if [[ $1 == -h ]]; then
    cat help
elif [[ $1 == -c ]]; then
    op config
elif [[ $1 == -* ]]; then
    ./bin/cmd "$@"
else
    ./app "$@"
fi
